### ISSUE TITLE
 qualified method is not used in mapping collections

### ISSUE THREAD

**Issue by natash** [mapstruct/mapstruct.org#16]
Hi, 

I have noticed interesting befaviour that I don't know if it is intended or not. I will try to explain it with example:

    //first mapper
    @Mappings({ @Mapping(source = "game.players", target = "players", qualifiedBy = QualifyPlayerMapper.class) })
    TargetGame mapGame(Game game);
   
    //second mapper
    @Mappings({ @Mapping(source = "player.street", target = "addressStreet")})
    TargetPlayer mapPlayer(Player player);
       
    //some mapping method that I wanna use and it is qualiffied
    @QualifyPlayerMapper
    TargetPlayer mapPlayerMyWay(Player player);
   
    so in the generated class, in the playerCollectionToPlayerCollection method, is used  mapPlayer.
    In my opinion it should use the second method - mapPlayerMyWay
   
   
    Regards,
    Natalia

**Comment by agudian** [comment]
@natash, this is the repository for the mapstruct.org website. Since we can't "move" the issue, could you please file it again directly in the repository for MapStruct itself? https://github.com/mapstruct/mapstruct/issues

Then you'll be notified automatically as soon as we fixed the issue. I'm closing this one here now.

Sorry for the inconvenience... :wink:
