### ISSUE TITLE
Correct reference guide links

### ISSUE THREAD

**Issue by chris922** [mapstruct/mapstruct.org#89]
I just noticed that the links to the 1.3.0.Final guides still contain `dev` in the URL and for 1.2.0.Final it is `stable`:

1.3.0.Final: http://mapstruct.org/documentation/dev/reference/html/
1.2.0.Final: http://mapstruct.org/documentation/stable/reference/html/

**Comment by filiphr** [comment]
Not sure that I am following @chris922. Where are these links? Or are you talking about the actual content behind them? Both links point to 1.3.0.Final for me

**Comment by chris922** [comment]
Oh sorry, would be a good idea to mention also the source page: http://mapstruct.org/documentation/reference-guide/

Take a look at the used links for 1.3.0.Final and 1.2.0.Final

Oh, and I should haven taken a deeper look at the `stable` link.. yes the content is correct. But then an invalid link is provided on the `reference-guide` page for 1.2.0.Final.

**Comment by filiphr** [comment]
Yes you are right, the used links on the reference-guide page is wrong for 1.2.0.Final

**Comment by chris922** [comment]
@filiphr are you able to update the mapstruct.org page with the changes? A new ticket regarding this was just raised (mapstruct/mapstruct#1796)

**Comment by filiphr** [comment]
@chris922 unfortunately I can't. I am on vacation and don't have access to my laptop 😀. However, I think that you can. Have a look at http://mapstruct.org/development/updating-mapstructorg/. The publish script has everything, it even forces you to use fix hugo version due to some casing issue we had. You'll need to manually install that hugo, it's not on homebrew 😀

**Comment by chris922** [comment]
Ah perfect! I just updated the page, thanks for the information and have a nice vacation!
